import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import NavBar from './components/NavBar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<main className='flex min-h-screen flex-col bg-slate-50 dark:bg-[#121212] px-4 lg:px-12'>
						<NavBar />
						<div className='container mx-auto mt-40'>
							{children}
							<hr />
						</div>
						<Footer />
					</main>
				</Providers>
			</body>
		</html >
	);
}
